steps:
  - name: maven:latest
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
artifacts:
  objects:
    location: 'gs://cicd/artifacts/'
    paths: ['target/*.jar']

steps:
  - name: node:latest
    dir: 'node'
    entrypoint: 'npm'
    args: ['install']

steps:
  - name: 'docker:stable'
    args: ['build', '-t', 'docker.io/choca777/cicd1:latest7', '.']
images: ['docker.io/choca777/cicd1:latest7']


#steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/cicd/cicd7', '.']
#images: ['gcr.io/cicd/cicd7']
