steps:
  - name: maven:latest
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
    
steps:
  - name: node:latest
    dir: 'node'
    entrypoint: 'npm'
    args: ['install']

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cicd/cicd7', '.']
artifacts:
  objects:
    location: ['gs://my-bucket/artifacts/']
    paths:
    - "target/*.jar"
images: ['gcr.io/cicd/cicd7']
