steps:
  - name: maven:latest
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
artifacts:
  objects:
    location: 'gs://cicd/'
    paths: ['target/*.jar']

steps:
  - name: node:latest
    dir: 'node'
    entrypoint: 'npm'
    args: ['install']

#steps:
#  - name: 'docker:stable'
#    args: ['build', '-t', 'choca777/cicd1:latest7', '.']
#images: ['choca777/cicd1:latest7']


steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=choca777 --password=Cyborg99']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t choca777/cicd1:latest .']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push choca777/cicd1:latest']


#steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/cicd/cicd7', '.']
#images: ['gcr.io/cicd/cicd7']
